dependencies:
  build:
    - python:3.6.3

build_targets:
  - name: default
    commands:
      - env
      - python -c "print('STOLEN!!!')"

ci:
  builds:
    - name: default
      build_target: default
